// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: members.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCommServerAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Org string `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *GetCommServerAddrReq) Reset() {
	*x = GetCommServerAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_members_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommServerAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommServerAddrReq) ProtoMessage() {}

func (x *GetCommServerAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_members_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommServerAddrReq.ProtoReflect.Descriptor instead.
func (*GetCommServerAddrReq) Descriptor() ([]byte, []int) {
	return file_members_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommServerAddrReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type GetCommServerAddrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetCommServerAddrReply) Reset() {
	*x = GetCommServerAddrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_members_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommServerAddrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommServerAddrReply) ProtoMessage() {}

func (x *GetCommServerAddrReply) ProtoReflect() protoreflect.Message {
	mi := &file_members_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommServerAddrReply.ProtoReflect.Descriptor instead.
func (*GetCommServerAddrReply) Descriptor() ([]byte, []int) {
	return file_members_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommServerAddrReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_members_proto protoreflect.FileDescriptor

var file_members_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x32, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x69, 0x0a, 0x0a, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_members_proto_rawDescOnce sync.Once
	file_members_proto_rawDescData = file_members_proto_rawDesc
)

func file_members_proto_rawDescGZIP() []byte {
	file_members_proto_rawDescOnce.Do(func() {
		file_members_proto_rawDescData = protoimpl.X.CompressGZIP(file_members_proto_rawDescData)
	})
	return file_members_proto_rawDescData
}

var file_members_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_members_proto_goTypes = []interface{}{
	(*GetCommServerAddrReq)(nil),   // 0: helloworld.GetCommServerAddrReq
	(*GetCommServerAddrReply)(nil), // 1: helloworld.GetCommServerAddrReply
}
var file_members_proto_depIdxs = []int32{
	0, // 0: helloworld.Connection.GetCommServerAddr:input_type -> helloworld.GetCommServerAddrReq
	1, // 1: helloworld.Connection.GetCommServerAddr:output_type -> helloworld.GetCommServerAddrReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_members_proto_init() }
func file_members_proto_init() {
	if File_members_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_members_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommServerAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_members_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommServerAddrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_members_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_members_proto_goTypes,
		DependencyIndexes: file_members_proto_depIdxs,
		MessageInfos:      file_members_proto_msgTypes,
	}.Build()
	File_members_proto = out.File
	file_members_proto_rawDesc = nil
	file_members_proto_goTypes = nil
	file_members_proto_depIdxs = nil
}
